-- Vymyslete a vepiště níže vlastní SQL dotaz, který bude zajímavým způsobem 
-- (!!!dotazy 09, 10, 11 budou významově originální, ne jen vzájemné doplňky!!!)
-- pomocí prostorových fukncí filtrovat body nálezů z Vašeho území. 
-- Nápověda: můžete si definovat a vkládat do WHERE dotazu i vlastní geometrie třeba pomocí ST_GeometryFromText
-- V SELECTu musí být povinně použity tyto položky:
-- gbifID, scientificName, ST_AsText(souradnice) AS souradniceWKT
-- Navržený dotaz bude povinně bude využívat alespoň jednu ST_ funkci z každého z těchto dvou odkazů: 
-- https://mariadb.com/kb/en/library/geometry-relations/ a https://mariadb.com/kb/en/library/geometry-constructors/
-- Zdůvodněte zde do poznámky, co je cílem Vámi navrhnutého SQL dotazu.
