-- Enter an SQL query below: 
-- SELECT will contain: *, ST_AsText (coordinates) AS coordinatesWKT 
-- in FROM clause you will connect via INNER JOIN:
--   1) event table with occurrence table via event.gbifID=occurrence.event_gbifID
--   2) and then the occurence table with the taxon table via occurrence.taxon_taxonKey=taxon.taxonKey
